package anykey;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Arun Guni Vines
 */
public class presskey extends javax.swing.JFrame {

    /**
     * Creates new form anykey
     */
    public presskey() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clickbutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 600));
        getContentPane().setLayout(null);

        clickbutton.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        clickbutton.setText("Click here to Play Bounce Ball");
        clickbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickbuttonMouseClicked(evt);
            }
        });
        clickbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(clickbutton);
        clickbutton.setBounds(30, 150, 830, 70);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-130, -30, 1280, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clickbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickbuttonActionPerformed
        setVisible(false);
        BounceBall1.main1();  //  bounce = new BounceBall1();
                              // bounce.setVisible(true);
    }//GEN-LAST:event_clickbuttonActionPerformed

    private void clickbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickbuttonMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_clickbuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(presskey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(presskey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(presskey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(presskey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new presskey().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clickbutton;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
